### ISSUE TITLE
Auto Sync LingQ Error

### ISSUE THREAD

**Issue by caltran117** [CiaranCurran/auto-sync-lingq#2]
Hey, thanks for creating the add-on for LingQ. I just downloaded it to use for the first time and I logged into my LingQ from the Anki. When I need to select a language to upload my LingQ words, I get an error but the deck does get uploaded to my Anki but it is missing alot of cards (which I compared with LingQ website). Here is the error code: 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-05-23 23:08:10

Caught exception:
Traceback (most recent call last):
  File "C:\Users\caltr\AppData\Roaming\Anki2\addons21\1151761316\dialog.py", line 125, in import_attempt
    sync_info = lingq_select_languages()
  File "C:\Users\caltr\AppData\Roaming\Anki2\addons21\1151761316\dialog.py", line 325, in lingq_select_languages
    sync_info = lingq_sync_cards()
  File "C:\Users\caltr\AppData\Roaming\Anki2\addons21\1151761316\dialog.py", line 376, in lingq_sync_cards
    note["Back"] = card["hints"][0]["text"]
IndexError: list index out of range

**Comment by Lanpice** [comment]
I'm having the same issue.

Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-05-31 15:27:33

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 52, in handler
  File "aqt\main.py", line 138, in on_window_init
  File "aqt\main.py", line 186, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 227, in setupProfile
  File "aqt\main.py", line 406, in loadProfile
  File "aqt\hooks_gen.py", line 2140, in __call__
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1151761316\plugin.py", line 27, in run_sync
    sync_info = lingq_sync_cards()
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1151761316\dialog.py", line 376, in lingq_sync_cards
    note["Back"] = card["hints"][0]["text"]
IndexError: list index out of range
